//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AvaliacaoPratica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pratos
    {
        public int PratoId { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "O campo nome deve ser preenchido.")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string PratoNome { get; set; }

        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "O campo descrição deve ser preenchido.")]
        public string PratoDescricao { get; set; }

        [Display(Name = "Preço")]
        [Required(ErrorMessage = "O campo preço deve ser preenchido.")]
        public decimal Preco { get; set; }

        [Display(Name = "Restaurante")]
        public int FK_RestauranteId { get; set; }
    
        public virtual Restaurantes Restaurantes { get; set; }
    }
}
