//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace AvaliacaoPratica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurantes
    {
        public Restaurantes()
        {
            this.Pratos = new HashSet<Pratos>();
        }
    
        public int RestauranteId { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "O campo nome deve ser preenchido.")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres.")]
        public string RestauranteNome { get; set; }

        [Display(Name = "Endereço")]
        [Required(ErrorMessage = "O campo endereço deve ser preenchido.")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres.")]
        public string Endereco { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "O campo telefone deve ser preenchido.")]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "Telefone deve possuir no mínimo 8 caracteres.")]
        public string Telefone { get; set; }
    
        public virtual ICollection<Pratos> Pratos { get; set; }
    }
}
